name: NcProperty
main: nx.property.core.Core
version: 0.0.1
author: WeiNaite
description: This is a player base data value on RPG games.

commands:
    np:
      description: Player user main commands.