name: NcMultiSystem
main: nx.property.core.Core
version: 0.0.1
authors: [WeiNaite, WiwiHo]
description: This is a player base data value on RPG games.

commands:
    property:
      aliases: [pro, np]
      description: Get player info.