name: NcMultiSystem
main: nx.multisystem.NcMultiSystem
version: 0.0.1
authors: [WeiNaite, WiwiHo]
description: This is a player base data value on RPG games.

commands:
  property:
    aliases: [pro, np]
    description: Get player info.
  propertyadmin:
    aliases: [proadmin, npadmin]
    description: Admin command about property.